try {
const __status = document.getElementById("status");
if (__status) __status.textContent = "Crawl engine is executing…";
"use strict";
const STORAGE_KEY="tlc-storyworks-prototype-crawl",MAX_STEPS=6;
const STORY=[
{label:"The Platform",text:"The station clock says 12:07. Your ticket says 12:07. There is no train listed on the departure board, but a dark train is waiting at the far platform anyway. Its windows glow with warm yellow light."},
{label:"The First Carriage",text:"The doors close behind you with a soft click. Nobody asks where you are going. Instead, the conductor hands you a blank ticket and says, “You will know your stop when you have written it.”"},
{label:"Between Stations",text:"Outside the window there are no towns, no roads, and no stars—only darkness. Somewhere farther down the train, a bell rings once."},
{label:"The Last Carriage",text:"The train begins to slow. You see a platform outside, but the station sign has been painted over. Something about the place feels familiar."},
{label:"The Door",text:"The conductor waits beside the exit. “One last thing,” they say. “Before you leave, decide what this journey was really about.”"},
{label:"The Destination",text:"The doors open. The platform is quiet. Your blank ticket now has words on it—your words. Whatever happens next belongs to the story you write from here."}];
const ENCOUNTERS=[
{kind:"sprint",title:"The Passenger in Seat 13",body:"Someone sits alone beneath a reading lamp. The rest of the carriage is empty. You pass their seat once, then twice. The third time, the passenger looks up. “You’ve been avoiding me,” they say. You are certain you have never seen them before—but they seem certain they know you.",action:"Write for 8 minutes about what happens when your protagonist finally sits down. Why does this stranger seem to know them, and what do they want?",reward:w=>w>=400?{tickets:1,clues:1,message:"The passenger smiles. You found a clue and a ticket."}:w>=200?{clues:1,message:"The passenger answers one question. You found a clue."}:{message:"The passenger turns back to their book. You keep moving."}},
{kind:"prompt",title:"The Window That Remembers",body:"The darkness outside the train begins to change. At first your protagonist thinks they are seeing a reflection. Then the window shows a street they have never visited. And yet they recognize it: the buildings, the broken curtain, the alley behind the shop. They even know what waits around the corner.",action:"Write at least 250 words about the place your protagonist somehow remembers perfectly. What happened there—and how can they remember somewhere they have never been?",reward:w=>w>=400?{tickets:1,clues:1,message:"The remembered place feels almost real. It leaves you a clue and a ticket."}:w>=250?{tickets:1,message:"The remembered place leaves a ticket in your pocket."}:{message:"The memory fades, but the journey continues."}},
{kind:"choice",title:"Two Doors",body:"At the end of the carriage are two doors. One is marked ARRIVALS. The other is marked DEPARTURES. Neither door was there the last time your protagonist looked.",action:"Choose a door, then write 300 words about what your protagonist finds beyond it.",choices:[{label:"Arrivals",clue:1,text:"Someone—or something—has been waiting for your protagonist.",instruction:"Write at least 300 words about what has been waiting, why it knows your protagonist, and what happens when they finally meet."},{label:"Departures",ticket:1,text:"The door opens onto a way out—but the path leads somewhere unexpected.",instruction:"Write at least 300 words about where the unexpected departure takes your protagonist and why they cannot simply turn around."}]},
{kind:"constraint",title:"The Conductor’s Rule",body:"The conductor appears without warning and gives your protagonist a strange instruction. “For the next few minutes,” they say, “you may not use the word I.” They tap the blank ticket. “The train is listening.”",action:"Write at least 300 words for a scene in which nobody says the word “I.” Make the restriction matter to what the characters are trying to say.",reward:w=>w>=500?{tickets:1,clues:2,message:"You followed the rule so completely that the conductor punches a ticket and gives you a clue."}:w>=300?{tickets:1,clues:1,message:"You followed the rule. The conductor punches your ticket and whispers a clue."}:{message:"The conductor lets it slide. This time."}},
{kind:"prompt",title:"The Bell",body:"A bell rings somewhere farther down the train. Once. Then silence. Your protagonist notices that nobody else reacts—not the conductor, not the other passengers, not even the person in Seat 13.",action:"Write at least 200 words explaining what the bell means. Whatever you decide, make its meaning matter later in the story.",reward:w=>w>=350?{clues:2,message:"The bell’s meaning becomes impossible to ignore. You found two clues."}:w>=200?{clues:1,message:"The bell’s meaning becomes a clue for the final stop."}:{message:"The bell rings again. You keep moving."}},
{kind:"prompt",title:"The Empty Seat",body:"One seat across the aisle is empty, but someone has left something behind. It is an ordinary object—until your protagonist touches it. Then they know, with absolute certainty, that they cannot leave it on the train.",action:"Write at least 250 words about the object, why it matters, and what your protagonist is willing to risk rather than leave it behind.",reward:w=>w>=400?{tickets:1,clues:1,message:"Whatever was left behind seems to know more than it should. You keep it—and find a ticket."}:w>=250?{clues:1,message:"Whatever was left behind seems to know more than it should."}:{message:"You leave the object where you found it. For now."}},
{kind:"constraint",title:"The Announcement",body:"The speakers crackle to life. Static fills the carriage, followed by a voice that sounds almost familiar. “Passengers are reminded that the next stop is…” The announcement cuts out.",action:"Write at least 300 words about what your protagonist hears when the announcement resumes. Include the exact phrase “next stop” somewhere in your writing, and make the announcement change what they thought this journey was about.",reward:w=>w>=500?{tickets:2,message:"The announcement gives you two tickets to somewhere unexpected."}:w>=300?{tickets:1,message:"The announcement gives you a ticket to somewhere unexpected."}:{message:"The speakers fall silent before the announcement is complete."}},
{kind:"sprint",title:"The Reflection",body:"The window catches your protagonist’s reflection—but for one moment, it moves differently. It turns its head before they do. It raises a hand before they do. Then it looks directly at them.",action:"Write for 6 minutes about why the reflection is moving on its own and what it wants your protagonist to understand.",reward:w=>w>=500?{tickets:1,clues:2,message:"The reflection finally moves with you. It leaves behind two clues and a ticket."}:w>=300?{tickets:1,clues:1,message:"The reflection finally moves with you. It leaves behind a clue and a ticket."}:w>=150?{clues:1,message:"The reflection stops moving. You found a clue, but not an answer."}:{message:"The reflection stops moving. Whatever it was, it isn’t following you."}},
{kind:"choice",title:"The Wrong Station",body:"The train stops. Outside the window is a station your protagonist recognizes immediately. The name on the sign is their hometown. The trouble is, it is not their hometown. Someone on the platform waves as though they have been waiting all night.",action:"Choose what your protagonist does, then write at least 300 words about the consequences.",choices:[{label:"Get off",clue:1,text:"Your protagonist steps onto the impossible platform. The person waiting there says their name.",instruction:"Write at least 300 words about who is waiting and what they know that your protagonist does not."},{label:"Stay aboard",ticket:1,text:"Your protagonist refuses to leave. The doors close, and the person on the platform mouths one word before the train departs.",instruction:"Write at least 300 words about the word they see and what it makes your protagonist do next."}]},
{kind:"choice",title:"The Conductor’s Offer",body:"The conductor finds your protagonist between carriages. “I can answer one question,” they say. “But the train requires a fare.” They hold out their hand.",action:"Choose what your protagonist gives up, then write at least 250 words about the question and its answer—or the consequences of refusing.",choices:[{label:"Give a Ticket",costTicket:1,clue:2,text:"Your protagonist gives up one Ticket. The conductor promises an answer.",instruction:"Write at least 250 words about the question your protagonist most needs answered and the truth the conductor finally reveals."},{label:"Give a Clue",costClue:1,ticket:1,text:"Your protagonist offers one of the things they have learned. The conductor looks surprised.",instruction:"Write at least 250 words about what your protagonist gives away and what the conductor gives them in return."},{label:"Refuse",text:"Your protagonist refuses to pay. The conductor steps aside, but the train seems to notice.",instruction:"Write at least 300 words about what happens because your protagonist refused the offer. Keep every resource you have."}]},
{kind:"random",title:"The Clock That Won’t Move",body:"Every clock in the carriage reads 12:07. Your phone says 12:07 too. Your protagonist watches the second hand tick forward—and then return to the same place.",action:"Write at least 250 words about what happens when your protagonist tries to make the clock move. What is the train keeping frozen, and why?",reward:w=>w>=400?{clues:2,message:"The clock moves once. You see something you were not supposed to see."}:w>=250?{clues:1,message:"The clock refuses to move, but you learn something about why."}:{message:"The clock remains at 12:07."}},
{kind:"choice",title:"The Woman With Your Ticket",body:"A woman you have never met sits across from your protagonist. She is holding a ticket. It has your name on it. “I think this belongs to me,” she says.",action:"Choose how your protagonist responds, then write at least 300 words about the exchange.",choices:[{label:"Take it back",ticket:1,text:"Your protagonist takes the ticket. The woman does not resist—but she looks relieved.",instruction:"Write at least 300 words about why she had your ticket and what she was trying to prevent."},{label:"Ask why she has it",clue:1,text:"Your protagonist leaves the ticket where it is and asks the only question that matters.",instruction:"Write at least 300 words about what the woman knows and why she was carrying your name."},{label:"Let her keep it",text:"Your protagonist lets her keep the ticket. The woman looks startled by the choice.",instruction:"Write at least 300 words about what changes because your protagonist gives up something that was supposed to belong to them."}]},
{kind:"prompt",title:"The Station That Isn’t There",body:"The train passes a platform with no tracks leading to it. There are benches, lamps, and a station clock, but nothing connects the platform to the world outside. As the train passes, your protagonist sees someone sitting there.",action:"Write at least 300 words about who is waiting on the impossible platform and why they cannot board the train.",reward:w=>w>=500?{clues:2,tickets:1,message:"The person on the platform leaves you a clue and a ticket before the station disappears."}:w>=300?{clues:1,message:"The impossible station leaves you with one important clue."}:{message:"The platform vanishes into the darkness."}},
{kind:"choice",title:"Someone Wants Your Seat",body:"Your protagonist returns to their seat and finds someone else sitting there. The stranger looks up and says, “You will need to decide whether this seat is really yours.” They do not move.",action:"Choose what your protagonist does, then write at least 250 words about the encounter.",choices:[{label:"Demand the seat",ticket:1,text:"Your protagonist insists. The stranger stands, but leaves something tucked beneath the cushion.",instruction:"Write at least 250 words about what was left behind and why the stranger wanted your seat."},{label:"Offer the seat",clue:1,text:"Your protagonist offers the seat freely. The stranger asks why.",instruction:"Write at least 250 words about the conversation that follows and what your protagonist learns by giving up their place."},{label:"Sit beside them",text:"Your protagonist refuses to make it a contest and sits beside the stranger instead.",instruction:"Write at least 300 words about what the stranger says when there is nowhere left to hide from the conversation."}]},
{kind:"constraint",title:"Write the Same Moment Twice",body:"The train passes through a tunnel. For a heartbeat, your protagonist experiences the same moment twice: once as it happens, and once as though remembering it.",action:"Write at least 300 words describing the same event twice. The second version must reveal something the first version did not.",reward:w=>w>=500?{clues:2,message:"The second version reveals something the train was hiding. Two clues emerge."}:w>=300?{clues:1,message:"The second version reveals a hidden connection. You gain a clue."}:{message:"The two versions blur together, leaving the truth uncertain."}},
{kind:"choice",title:"The Last Stop",body:"A handwritten sign appears on the carriage wall: LAST STOP. The conductor sees your protagonist reading it and says, very quietly, “It doesn’t have to be yours.”",action:"Choose what your protagonist does with the warning, then write at least 300 words about the choice.",choices:[{label:"Ask for the last stop",clue:1,text:"Your protagonist asks where the train is really going.",instruction:"Write at least 300 words about the answer and why knowing it changes what your protagonist wants."},{label:"Ignore the warning",ticket:1,text:"Your protagonist decides the sign is not a command.",instruction:"Write at least 300 words about what happens when they deliberately continue toward a destination they were warned about."}]},
{kind:"random",title:"The Carriage With No Door",body:"There is a carriage ahead that your protagonist has not seen before. The passage between cars is open, but there is no door at the far end—only darkness where the next carriage should be.",action:"Write at least 250 words about what your protagonist finds in the impossible carriage and why the train has hidden it.",reward:w=>w>=400?{tickets:1,clues:1,message:"The impossible carriage gives up a ticket and a clue."}:w>=250?{tickets:1,message:"You find a ticket where no ticket should be."}:{message:"The darkness closes before you can see what was inside."}},
{kind:"choice",title:"The Thing You Left Behind",body:"Something appears on the seat beside your protagonist. It is something they lost long before boarding the train. They know exactly when they lost it. They also know they cannot take it with them without giving something else up.",action:"Choose what your protagonist does, then write at least 300 words about what they recover—or what they choose to leave behind.",choices:[{label:"Take it",clue:1,text:"Your protagonist takes back what was lost. The train immediately asks for a price.",instruction:"Write at least 300 words about what the train takes in return."},{label:"Leave it",ticket:1,text:"Your protagonist leaves the object where it is. The train seems almost disappointed.",instruction:"Write at least 300 words about why your protagonist chooses not to reclaim it and what that choice changes."},{label:"Give it away",text:"Your protagonist offers the lost thing to another passenger.",instruction:"Write at least 300 words about who accepts it and why giving it away is harder than keeping it."}]},
{kind:"prompt",title:"The Passenger Who Has Already Arrived",body:"A passenger walks through the carriage carrying a coat damp with rain. They stop beside your protagonist and say, “I was on this train yesterday.” Then they add, “You were here too.”",action:"Write at least 300 words about the conversation. Decide whether your protagonist believes them, and reveal one thing they remember that your protagonist does not.",reward:w=>w>=500?{clues:2,tickets:1,message:"Their memory fills in a missing piece of the journey. You gain two clues and a ticket."}:w>=300?{clues:1,message:"Their memory fills in one missing piece of the journey."}:{message:"The passenger moves on before your protagonist can decide whether to believe them."}},
{kind:"choice",title:"The Light Between Cars",body:"A thin line of warm light shines beneath the door between carriages. Your protagonist is certain the train has been dark beyond that door until now. Something on the other side knocks three times.",action:"Choose whether your protagonist opens the door, then write at least 300 words about what answers the knock.",choices:[{label:"Open the door",clue:1,text:"Your protagonist opens the door. The light beyond it is brighter than it should be.",instruction:"Write at least 300 words about what is waiting there and why it wanted your protagonist to open the door."},{label:"Keep it closed",ticket:1,text:"Your protagonist keeps the door closed. The knocking stops—but something slides underneath.",instruction:"Write at least 300 words about what was left behind and what your protagonist does with it."}]},
{kind:"random",title:"The Blank Page",body:"The blank ticket is not the only thing the train has given your protagonist. On the seat beside them is a sheet of paper with nothing written on it. When they look away, a single sentence appears.",action:"Write at least 250 words beginning with the sentence: “You were supposed to remember this.” Continue the scene from there.",reward:w=>w>=400?{clues:2,message:"The page fills itself with a second sentence. You gain two clues."}:w>=250?{clues:1,message:"The page gives you one answer—and another question."}:{message:"The sentence disappears before another can appear."}}
];
const els={sceneLabel:document.getElementById("scene-label"),sceneText:document.getElementById("scene-text"),encounterLabel:document.getElementById("encounter-label"),encounterTitle:document.getElementById("encounter-title"),encounterBody:document.getElementById("encounter-body"),encounterPanel:document.getElementById("encounter-panel"),challengeControls:document.getElementById("challenge-controls"),start:document.getElementById("start-button"),reset:document.getElementById("reset-button"),progressText:document.getElementById("progress-text"),progressCount:document.getElementById("progress-count"),progressFill:document.getElementById("progress-fill"),progressBar:document.querySelector(".progress-track"),tickets:document.getElementById("tickets"),clues:document.getElementById("clues"),words:document.getElementById("words"),status:document.getElementById("status")};
function freshState(){return{active:false,complete:false,phase:"idle",step:0,tickets:0,clues:0,words:0,used:[],current:null,doorOutcome:null}}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return s&&typeof s==="object"?{...freshState(),...s}:freshState()}catch{return freshState()}}
let state=loadState();
let selectedChoice=null;
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{setStatus("Your browser is blocking saved crawl progress. The crawl can still continue in this tab.")}}
function setStatus(m){els.status.textContent=m||""}
function updateStats(){els.tickets.textContent=state.tickets;els.clues.textContent=state.clues;els.words.textContent=state.words.toLocaleString()}
function updateProgress(){const v=Math.min(state.step,MAX_STEPS);els.progressCount.textContent=v+" / "+MAX_STEPS;els.progressFill.style.width=v/MAX_STEPS*100+"%";els.progressBar.setAttribute("aria-valuenow",String(v));els.progressText.textContent=state.complete?"Journey complete":v===0?"The journey begins":"The journey continues"}
function getResourceOutcome(){
if(state.doorOutcome==="both")return{key:"both",door:"The conductor looks at your collection of punched tickets, then at the clues you have gathered. “You figured it out,” they say. “And you earned your way here.”",destination:"The train seems to recognize you. You spent your tickets to earn passage, and the clues you gathered let you understand why the train came for you. The door opens. What happens next belongs to the story you write from here."};
const t=state.tickets,c=state.clues;
if(t>=2&&c>=2)return{key:"both",door:"The conductor looks at your collection of punched tickets, then at the clues you have gathered. “You figured it out,” they say. “And you earned your way here.”",destination:"The train seems to recognize you. Your ticket is complete, and the pieces of the journey finally fit together. You understand why this train came for you—and you have earned the right to decide where it goes next."};
if(t>=2)return{key:"tickets",door:"The conductor studies your punched tickets. “You have earned your passage,” they say. But their expression suggests there is still something you have missed.",destination:"The doors open without resistance. You have earned your way off the train, even if some of its mysteries remain. Perhaps understanding can come later—or perhaps it belongs in the story you write next."};
if(c>=2)return{key:"clues",door:"The conductor listens as you explain what you have learned. “You understand more than most passengers do,” they say. Then they glance toward the locked door. “Understanding and permission are not quite the same thing.”",destination:"The doors open, but not quite where you expected. You understand what the train was trying to show you, even if you never quite earned a normal ticket out. The mystery follows you into whatever story comes next."};
return{key:"neither",door:"The conductor looks at your blank ticket. “You made it this far,” they say. “But perhaps you were never meant to understand the journey—or earn your way out of it.”",destination:"The doors open onto an unfamiliar platform. You leave with more questions than answers, carrying only the words you wrote along the way. Maybe that is exactly what the journey was for."};
}
function renderStory(i){
const s=STORY[Math.min(i,STORY.length-1)];
els.sceneLabel.textContent=s.label;
let text=s.text;
if(i===4)text=getResourceOutcome().door;
if(i===5)text=getResourceOutcome().destination;
els.sceneText.innerHTML="<p>"+text+"</p>";
}
function chooseEncounter(){let pool=ENCOUNTERS.filter((e,i)=>!state.used.includes(i)&&(e.minStep==null||state.step>=e.minStep)&&(e.maxStep==null||state.step<=e.maxStep));if(!pool.length)pool=ENCOUNTERS.filter((e,i)=>!state.used.includes(i));if(!pool.length)pool=ENCOUNTERS.filter((_,i)=>i!==state.current);if(!pool.length)pool=ENCOUNTERS;const e=pool[Math.floor(Math.random()*pool.length)],ri=ENCOUNTERS.indexOf(e);state.used.push(ri);state.current=ri;return e}
function showEncounter(e){
els.encounterPanel.hidden=false;
els.encounterLabel.textContent=e.kind==="choice"?"Choice encounter":e.kind==="sprint"?"Timed writing":"Writing challenge";
els.encounterTitle.textContent=e.title;
els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>"+e.body+"</p><div class=\"encounter-prompt\"><p><strong>"+e.action+"</strong></p>";
els.challengeControls.innerHTML="";
const b=document.createElement("button");b.type="button";b.className="primary";b.textContent=e.kind==="choice"?"Choose your path":"Begin writing";b.addEventListener("click",()=>beginChallenge(e));els.challengeControls.appendChild(b);
}
function addWordInput(onComplete){
const l=document.createElement("label");l.className="word-entry";l.innerHTML='<span>Words written</span> <input id="challenge-words" type="number" min="0" inputmode="numeric" value="0">';
const b=document.createElement("button");b.type="button";b.className="primary";b.textContent="Complete challenge";
b.addEventListener("click",()=>{const w=Math.max(0,Number(document.getElementById("challenge-words").value)||0);onComplete(w)});
els.challengeControls.append(l,b);document.getElementById("challenge-words").focus()
}
function beginChallenge(e){
els.encounterPanel.hidden=false;
els.encounterLabel.textContent=e.kind==="choice"?"Choice encounter":e.kind==="sprint"?"Timed writing":"Writing challenge";
els.encounterTitle.textContent=e.title;
els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>"+e.body+"</p><div class=\"encounter-prompt\"><p><strong>"+e.action+"</strong></p>";
els.challengeControls.innerHTML="";
if(e.kind==="choice"){
selectedChoice=null;
const choiceLead=document.createElement("p");choiceLead.className="choice-lead";choiceLead.innerHTML="<strong>Choose what your protagonist does:</strong>";els.challengeControls.appendChild(choiceLead);
e.choices.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="primary choice-button";b.textContent=c.label;b.addEventListener("click",()=>{
selectedChoice=c;const cost=c.costTicket||0,clueCost=c.costClue||0;
if(state.tickets<cost||state.clues<clueCost){setStatus("You do not have the resource required for that choice.");return}
state.tickets-=cost;state.clues-=clueCost;
els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>"+e.body+"</p><div class=\"encounter-choice\"><p class=\"choice-result\"><strong>"+c.text+"</strong></p><p>"+c.instruction+"</p>";
els.challengeControls.innerHTML="";addWordInput(w=>finishChallenge({words:w,tickets:c.ticket||0,clues:c.clue||0,message:c.text}));updateStats();save()
});els.challengeControls.appendChild(b)});return}
addWordInput(w=>finishChallenge({words:w}))
}
function showResourceGate(){
state.phase="door";state.current=null;els.encounterPanel.hidden=false;els.encounterLabel.textContent="The Door";els.challengeControls.innerHTML="";
if(state.tickets<2){
els.encounterTitle.textContent="Earn Your Passage";els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>The conductor holds out a hand. “Ticket.”</p><p>You show what you have. They shake their head.</p><div class=\"encounter-prompt\"><p><strong>Write at least 250 words</strong> about a moment when your protagonist earns the right to continue somewhere they were not expected to enter.</p><p>Your writing will earn you one Ticket.</p>";
addWordInput(w=>{state.words+=w;if(w>=250){state.tickets++;setStatus("The conductor punches your ticket. Passage earned.");updateStats();updateProgress();save();showResourceGate()}else{setStatus("The conductor shakes their head. You need at least 250 words to earn passage.");updateStats();save()}});return;
}
if(state.clues<2){
els.encounterTitle.textContent="Find What Is Hidden";els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>The conductor studies your ticket. “You may have earned your passage,” they say, “but you still do not know enough.”</p><div class=\"encounter-prompt\"><p><strong>Write at least 250 words</strong> revealing a hidden connection between your protagonist and something they encountered on the train.</p><p>Your writing will earn you one Clue.</p>";
addWordInput(w=>{state.words+=w;if(w>=250){state.clues++;setStatus("Something clicks into place. You found a clue.");updateStats();updateProgress();save();showResourceGate()}else{setStatus("The connection is not clear enough yet. You need at least 250 words.");updateStats();save()}});return;
}
state.doorOutcome="both";state.tickets-=2;state.clues-=2;updateStats();save();setStatus("The conductor takes your tickets and studies the clues. The lock clicks.");showDoorFinalChallenge()
}
function showDoorFinalChallenge(){
state.phase="door-final";els.encounterPanel.hidden=false;els.encounterLabel.textContent="The Door";els.encounterTitle.textContent="What Was This Journey About?";els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>The conductor looks at the clues you gathered, then at the blank ticket that is no longer blank.</p><p>“You have earned the right to leave,” they say. “But before you go, decide what all of this meant.”</p><div class=\"encounter-prompt\"><p><strong>Write at least 300 words</strong> connecting something your protagonist encountered on the train to the reason the train came for them.</p><p>This is not another resource check. This is the piece of the story that belongs to you.</p>";els.challengeControls.innerHTML="";
addWordInput(w=>{state.words+=w;if(w>=300){state.phase="destination";state.step=5;state.current=null;updateStats();updateProgress();save();renderStory(5);showDestinationArrival()}else{setStatus("The conductor waits. You need at least 300 words to decide what the journey meant.");updateStats();save()}})
}
function showDestinationArrival(){
els.encounterPanel.hidden=false;els.encounterLabel.textContent="The Destination";els.encounterTitle.textContent="The doors open.";els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>"+getResourceOutcome().destination+"</p><div class=\"encounter-prompt\"><p><strong>Whatever happens next belongs to the story you write from here.</strong></p>";els.challengeControls.innerHTML="";const b=document.createElement("button");b.type="button";b.className="primary";b.textContent="Leave the train";b.addEventListener("click",finishCrawl);els.challengeControls.appendChild(b);setStatus("The door is open. The destination is yours.")
}
function finishChallenge(r){const e=ENCOUNTERS[state.current];state.words+=r.words||0;state.tickets+=r.tickets||r.ticket||0;state.clues+=r.clues||r.clue||0;if(e.reward){const x=e.reward(r.words||0);state.tickets+=x.tickets||0;state.clues+=x.clues||0;setStatus(x.message||"Challenge complete.")}else setStatus(r.message||"Challenge complete.");state.step++;updateStats();updateProgress();if(state.step===4){state.phase="door";state.current=null;renderStory(4);save();setTimeout(showResourceGate,500);return}if(state.step>=MAX_STEPS){finishCrawl();return}state.phase="encounter";renderStory(state.step);const n=chooseEncounter();save();setTimeout(()=>showEncounter(n),500)}
function finishCrawl(){state.step=MAX_STEPS;state.complete=true;state.active=false;state.phase="complete";state.current=null;save();updateStats();updateProgress();renderStory(STORY.length-1);els.encounterPanel.hidden=false;els.encounterLabel.textContent="The journey is complete";els.encounterTitle.textContent="You have reached the final stop.";els.encounterBody.innerHTML="<div class=\"encounter-story\"><p>Your ticket is covered in your own words. You leave the train carrying "+state.tickets+" ticket"+(state.tickets===1?"":"s")+" and "+state.clues+" clue"+(state.clues===1?"":"s")+".</p><div class=\"encounter-prompt\"><p><strong>There is only one question left: what happens next?</strong></p>";els.challengeControls.innerHTML="";els.start.textContent="Play again";setStatus("Crawl complete.")}
function start(){state=freshState();state.active=true;state.phase="encounter";renderStory(0);const e=chooseEncounter();updateStats();updateProgress();showEncounter(e);els.start.textContent="Restart crawl";setStatus("The train doors open.");save()}
function reset(){state=freshState();selectedChoice=null;save();renderStory(0);els.encounterPanel.hidden=false;els.encounterLabel.textContent="Your next stop";els.encounterTitle.textContent="A train waits where no train should be.";els.encounterBody.innerHTML="<p>When you are ready, board the train. Your route will contain a mixture of fixed story beats and random writing challenges.</p>";els.challengeControls.innerHTML="";const b=document.createElement("button");b.type="button";b.className="primary";b.textContent="Board the train";b.addEventListener("click",start);els.challengeControls.appendChild(b);els.start.textContent="Board the train";updateStats();updateProgress();setStatus("Crawl reset.")}
function continueToDestination(){
state.step=5;
state.current=null;
save();
updateStats();
updateProgress();
renderStory(STORY.length-1);
finishCrawl();
}
function finishChallenge(r){const e=ENCOUNTERS[state.current];state.words+=r.words||0;state.tickets+=r.tickets||r.ticket||0;state.clues+=r.clues||r.clue||0;if(e.reward){const x=e.reward(r.words||0);state.tickets+=x.tickets||0;state.clues+=x.clues||0;setStatus(x.message||"Challenge complete.")}else setStatus(r.message||"Challenge complete.");state.step++;updateStats();updateProgress();if(state.step===4){state.phase="door";state.current=null;renderStory(4);save();setTimeout(showResourceGate,500);return}if(state.step>=MAX_STEPS){finishCrawl();return}state.phase="encounter";renderStory(state.step);const n=chooseEncounter();save();setTimeout(()=>showEncounter(n),500)}
function finishCrawl(){state.step=MAX_STEPS;state.complete=true;state.active=false;state.phase="complete";state.current=null;save();updateStats();updateProgress();renderStory(STORY.length-1);els.encounterPanel.hidden=false;els.encounterLabel.textContent="The journey is complete";els.encounterTitle.textContent="You have reached the final stop.";els.encounterBody.innerHTML="<p>Your ticket is covered in your own words. You leave the train carrying "+state.tickets+" ticket"+(state.tickets===1?"":"s")+" and "+state.clues+" clue"+(state.clues===1?"":"s")+".</p><p><strong>There is only one question left: what happens next?</strong></p>";els.start.textContent="Play again";setStatus("Crawl complete.")}
function start(){state=freshState();state.active=true;state.phase="encounter";renderStory(0);const e=chooseEncounter();updateStats();updateProgress();showEncounter(e);els.start.textContent="Restart crawl";setStatus("The train doors open.");save()}
function reset(){state=freshState();selectedChoice=null;save();els.challengeControls.innerHTML="";renderStory(0);els.encounterPanel.hidden=false;els.encounterLabel.textContent="Your next stop";els.encounterTitle.textContent="A train waits where no train should be.";els.encounterBody.innerHTML="<p>When you are ready, board the train. Your route will contain a mixture of fixed story beats and random writing challenges.</p>";const b=document.createElement("button");b.type="button";b.className="primary";b.textContent="Board the train";b.addEventListener("click",start);els.challengeControls.appendChild(b);els.start.textContent="Board the train";updateStats();updateProgress();setStatus("Crawl reset.")}
els.start.addEventListener("click",start); els.reset.addEventListener("click",reset);renderStory(state.complete?STORY.length-1:state.step);updateStats();updateProgress();if(state.complete)finishCrawl();else if(state.active&&state.phase==="door"){showResourceGate()}else if(state.active&&state.phase==="door-final"){showDoorFinalChallenge()}else if(state.active&&state.phase==="destination"){showDestinationArrival()}else if(state.active&&state.current!==null){showEncounter(ENCOUNTERS[state.current]);els.start.textContent="Restart crawl"}
} catch (error) {
  const status = document.getElementById("status");
  if (status) status.textContent = "Crawl engine error: " + (error && error.message ? error.message : String(error));
  throw error;
}