(()=>{"use strict";
const STORAGE_KEY="tlc-storyworks-prototype-crawl",MAX_STEPS=6;
const STORY=[
{label:"The Platform",text:"The station clock says 12:07. Your ticket says 12:07. There is no train listed on the departure board, but a dark train is waiting at the far platform anyway. Its windows glow with warm yellow light."},
{label:"The First Carriage",text:"The doors close behind you with a soft click. Nobody asks where you are going. Instead, the conductor hands you a blank ticket and says, “You will know your stop when you have written it.”"},
{label:"Between Stations",text:"Outside the window there are no towns, no roads, and no stars—only darkness. Somewhere farther down the train, a bell rings once."},
{label:"The Last Carriage",text:"The train begins to slow. You see a platform outside, but the station sign has been painted over. Something about the place feels familiar."},
{label:"The Door",text:"The conductor waits beside the exit. “One last thing,” they say. “Before you leave, decide what this journey was really about.”"},
{label:"The Destination",text:"The doors open. The platform is quiet. Your blank ticket now has words on it—your words. Whatever happens next belongs to the story you write from here."}];
const ENCOUNTERS=[
{kind:"sprint",title:"The Passenger in Seat 13",body:"Someone sits alone beneath a reading lamp. You have eight minutes to write the scene in which your protagonist decides whether to speak to them.",action:"Write for 8 minutes, then enter the number of words you wrote.",reward:w=>w>=400?{tickets:1,clues:1,message:"The passenger smiles. You found a clue and a ticket."}:{clues:1,message:"The passenger smiles anyway. You found a clue."}},
{kind:"prompt",title:"The Window That Remembers",body:"Look out the window. Write at least 250 words about a place your protagonist has never visited—but somehow remembers perfectly.",action:"Enter the words you wrote when you're done.",reward:w=>w>=250?{tickets:1,message:"The remembered place leaves a ticket in your pocket."}:{message:"The memory fades, but the journey continues."}},
{kind:"choice",title:"Two Doors",body:"At the end of the carriage are two doors. One is marked <strong>ARRIVALS</strong>. The other is marked <strong>DEPARTURES</strong>.",action:"Choose a door, then write 300 words about what your protagonist finds beyond it.",choices:[{label:"Arrivals",clue:1,text:"Someone—or something—has been waiting for you."},{label:"Departures",ticket:1,text:"You find a way to leave, but it leads somewhere unexpected."}]},
{kind:"constraint",title:"The Conductor's Rule",body:"The conductor gives you a strange instruction: write a scene in which <strong>nobody says the word “I.”</strong>",action:"Write at least 300 words. When you finish, record your word count.",reward:w=>w>=300?{tickets:1,clues:1,message:"You followed the rule. The conductor punches your ticket."}:{message:"The conductor lets it slide. This time."}},
{kind:"random",title:"The Bell",body:"A bell rings. You have no idea what it means, so decide for yourself.",action:"Write 200 words explaining what the bell means—and make the answer matter.",reward:w=>w>=200?{clues:1,message:"The bell's meaning becomes a clue for the final stop."}:{message:"The bell rings again. You keep moving."}}
];
const els={sceneLabel:document.getElementById("scene-label"),sceneText:document.getElementById("scene-text"),encounterLabel:document.getElementById("encounter-label"),encounterTitle:document.getElementById("encounter-title"),encounterBody:document.getElementById("encounter-body"),encounterPanel:document.getElementById("encounter-panel"),challengePanel:document.getElementById("challenge-panel"),challengeType:document.getElementById("challenge-type"),challengeTitle:document.getElementById("challenge-title"),challengeBody:document.getElementById("challenge-body"),challengeControls:document.getElementById("challenge-controls"),start:document.getElementById("start-button"),reset:document.getElementById("reset-button"),progressText:document.getElementById("progress-text"),progressCount:document.getElementById("progress-count"),progressFill:document.getElementById("progress-fill"),progressBar:document.querySelector(".progress-track"),tickets:document.getElementById("tickets"),clues:document.getElementById("clues"),words:document.getElementById("words"),status:document.getElementById("status")};
function freshState(){return{active:false,complete:false,step:0,tickets:0,clues:0,words:0,used:[],current:null}}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return s&&typeof s==="object"?{...freshState(),...s}:freshState()}catch{return freshState()}}
let state=loadState();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function setStatus(m){els.status.textContent=m||""}
function updateStats(){els.tickets.textContent=state.tickets;els.clues.textContent=state.clues;els.words.textContent=state.words.toLocaleString()}
function updateProgress(){const v=Math.min(state.step,MAX_STEPS);els.progressCount.textContent=v+" / "+MAX_STEPS;els.progressFill.style.width=v/MAX_STEPS*100+"%";els.progressBar.setAttribute("aria-valuenow",String(v));els.progressText.textContent=state.complete?"Journey complete":v===0?"The journey begins":"The journey continues"}
function renderStory(i){const s=STORY[Math.min(i,STORY.length-1)];els.sceneLabel.textContent=s.label;els.sceneText.innerHTML="<p>"+s.text+"</p>"}
function chooseEncounter(){const a=ENCOUNTERS.filter((_,i)=>!state.used.includes(i)),pool=a.length?a:ENCOUNTERS,i=Math.floor(Math.random()*pool.length),e=pool[i],ri=ENCOUNTERS.indexOf(e);state.used.push(ri);state.current=ri;return e}
function showEncounter(e){els.encounterPanel.hidden=false;els.challengePanel.hidden=true;els.encounterLabel.textContent="Random encounter";els.encounterTitle.textContent=e.title;els.encounterBody.innerHTML="<p>"+e.body+"</p><p>"+e.action+"</p>";els.challengeControls.innerHTML="";const b=document.createElement("button");b.type="button";b.className="primary";b.textContent=e.kind==="choice"?"Make your choice":"Begin challenge";b.addEventListener("click",()=>beginChallenge(e));els.challengeControls.appendChild(b)}
function beginChallenge(e){els.encounterPanel.hidden=true;els.challengePanel.hidden=false;els.challengeType.textContent=e.kind==="sprint"?"Timed writing":e.kind==="choice"?"Choice + writing":"Writing challenge";els.challengeTitle.textContent=e.title;els.challengeBody.innerHTML="<p>"+e.body+"</p>";els.challengeControls.innerHTML="";
if(e.kind==="choice"){e.choices.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="primary";b.textContent=c.label;b.addEventListener("click",()=>finishChallenge({words:300,...c,message:c.text}));els.challengeControls.appendChild(b)});return}
const l=document.createElement("label");l.innerHTML="Words written <input id=\"challenge-words\" type=\"number\" min=\"0\" inputmode=\"numeric\" value=\"0\">";const b=document.createElement("button");b.type="button";b.className="primary";b.textContent="Complete challenge";b.addEventListener("click",()=>{const w=Math.max(0,Number(document.getElementById("challenge-words").value)||0);finishChallenge({words:w})});els.challengeControls.append(l,b);document.getElementById("challenge-words").focus()}
function finishChallenge(r){const e=ENCOUNTERS[state.current];state.words+=r.words||0;state.tickets+=r.ticket||0;state.clues+=r.clue||0;if(e.reward){const x=e.reward(r.words||0);state.tickets+=x.tickets||0;state.clues+=x.clues||0;setStatus(x.message||"Challenge complete.")}else setStatus(r.message||"Challenge complete.");state.step++;save();updateStats();updateProgress();if(state.step>=MAX_STEPS){finishCrawl();return}renderStory(state.step);const n=chooseEncounter();save();setTimeout(()=>showEncounter(n),250)}
function finishCrawl(){state.complete=true;state.active=false;state.current=null;save();renderStory(STORY.length-1);els.encounterPanel.hidden=false;els.challengePanel.hidden=true;els.encounterLabel.textContent="The journey is complete";els.encounterTitle.textContent="You have reached the final stop.";els.encounterBody.innerHTML="<p>Your ticket is covered in your own words. You leave the train carrying "+state.tickets+" ticket"+(state.tickets===1?"":"s")+" and "+state.clues+" clue"+(state.clues===1?"":"s")+".</p><p><strong>There is only one question left: what happens next?</strong></p>";els.start.textContent="Play again";setStatus("Crawl complete.")}
function start(){if(state.complete)state=freshState();state.active=true;state.complete=false;state.step=0;renderStory(0);const e=chooseEncounter();save();updateStats();updateProgress();showEncounter(e);els.start.textContent="Restart crawl";setStatus("The train doors open.")}
function reset(){state=freshState();save();renderStory(0);els.encounterPanel.hidden=false;els.challengePanel.hidden=true;els.encounterLabel.textContent="Your next stop";els.encounterTitle.textContent="A train waits where no train should be.";els.encounterBody.innerHTML="<p>When you are ready, board the train. Your route will contain a mixture of fixed story beats and random writing challenges.</p>";els.start.textContent="Board the train";updateStats();updateProgress();setStatus("Crawl reset.")}
els.start.addEventListener("click",start);els.reset.addEventListener("click",reset);renderStory(state.complete?STORY.length-1:state.step);updateStats();updateProgress();if(state.active&&!state.complete&&state.current!==null){showEncounter(ENCOUNTERS[state.current]);els.start.textContent="Restart crawl"}else if(state.complete)finishCrawl();
})();