const LOST_WOODS = {
  meta: {
    id: "lost-woods",
    title: "The Lost Woods",
    description: "A long branching word crawl about a forest that remembers everyone who enters it.",
    tags: { type: ["branching"], mechanics: ["choices", "flags", "exploration", "conditional-encounters"], length: ["long"], mood: ["mysterious", "whimsical", "adventurous"], format: ["story", "prompts"] }
  },
  encounters: [
    {id:"crow",title:"The Crow With Three Answers",tags:["animal","mystery"],body:"A crow lands on a branch above you. It offers to answer one question, but every answer will be true in a way you may not expect.",prompt:"Write 300 words about the question your protagonist asks—and the answer that leaves them with even more questions.",min:300,success:[{flag:"heardCrow",label:"Heard the crow's answer"}]},
    {id:"deer",title:"The Deer at the Boundary",tags:["animal","mystery"],body:"A white deer watches from between two trees. Whenever you approach, it appears a little farther away. When you turn back, it is standing behind you.",prompt:"Write 300 words about whether your protagonist follows the deer, challenges it, or asks it to lead the way.",min:300,success:[{flag:"followedDeer",label:"Followed the white deer"}]},
    {id:"rabbit",title:"The Rabbit That Speaks",tags:["animal","whimsical"],body:"A rabbit wearing a tiny blue waistcoat sits on a stump. “You're going the wrong way,” it says. “Of course, there isn't a right way. That's the trouble.”",prompt:"Write 300 words about the advice the rabbit gives—and why your protagonist might or might not trust it.",min:300,success:[{flag:"metRabbit",label:"Met the talking rabbit"}]},
    {id:"lantern-keeper",title:"The Lantern Keeper",tags:["person","object"],requires:["litLantern"],body:"A person carrying an unlit lantern steps out of the trees. They look at yours with unmistakable relief. “I wondered who had found it,” they say.",prompt:"Write 350 words about who the Lantern Keeper is and what they ask your protagonist to carry onward.",min:350,success:[{flag:"metKeeper",label:"Met the Lantern Keeper"}]},
    {id:"fox-return",title:"The Fox Remembers",tags:["animal"],requires:["helpedFox"],body:"The fox you helped trots out from the undergrowth. It circles your feet once, then looks pointedly toward a narrow path you hadn't noticed before.",prompt:"Write 300 words about where the fox leads your protagonist and what it expects in return.",min:300,success:[{flag:"foxGuided",label:"The fox guided you"}]},
    {id:"fox-stranger",title:"The Fox Who Keeps Its Distance",tags:["animal"],requires:["ignoredFox"],body:"A fox watches from the far side of the creek. It seems familiar, though you cannot say why. When you take a step toward it, it slips away into the ferns.",prompt:"Write 300 words about what your protagonist thinks the fox remembers—and whether they try to follow.",min:300,success:[{flag:"sawFoxAgain",label:"Saw the fox again"}]},
    {id:"familiar-path",title:"The Familiar Path",tags:["place","mystery"],body:"A path curves around an oak tree. You are certain you've passed this tree before. A scratch on its trunk looks exactly like a mark you made long ago.",prompt:"Write 350 words about what your protagonist remembers, or what they fear they are supposed to remember.",min:350,success:[{flag:"rememberedPath",label:"Recognized a path"}]},
    {id:"creek-crossing",title:"The Creek That Asks a Question",tags:["place","choice"],body:"The creek is narrow enough to step across, but the water flows uphill. A voice from beneath the stones asks, “What are you willing to leave on this bank?”",prompt:"Write 300 words about what your protagonist leaves behind—or why they refuse to leave anything at all.",min:300,success:[{flag:"crossedCreek",label:"Crossed the strange creek"}]},
    {id:"hollow",title:"The Hollow in the Hill",tags:["place","discovery"],body:"A small doorway has appeared in the side of a moss-covered hill. Warm air drifts from it, carrying the smell of bread and woodsmoke.",prompt:"Write 350 words about what your protagonist finds inside the hill and why the place feels as if it knows them.",min:350,success:[{flag:"foundHollow",label:"Explored the hollow"}]},
    {id:"camp",title:"The Abandoned Camp",tags:["place","object"],body:"A cold campfire sits among three bedrolls. A kettle still steams, and one of the bedrolls is unmistakably your protagonist's size.",prompt:"Write 350 words about who camped here and what they left behind for your protagonist to discover.",min:350,success:[{flag:"foundCamp",label:"Found the abandoned camp"}]},
    {id:"backpack",title:"The Missing Backpack",tags:["object","choice"],body:"A weathered backpack hangs from a branch. Inside are dry matches, a half-eaten apple, and a note: “If you found this, please don't make the same mistake I did.”",prompt:"Write 300 words about whether your protagonist takes the supplies, leaves them, or adds something of their own.",min:300,success:[{flag:"foundBackpack",label:"Found the backpack"}]},
    {id:"names",title:"The Names in the Tree",tags:["object","mystery"],body:"Hundreds of names have been carved into the bark of a fallen tree. Some are crossed out. One is your protagonist's—or a name they have tried to forget.",prompt:"Write 400 words about what the name means and what your protagonist does when they find it.",min:400,success:[{flag:"foundName",label:"Found a name in the tree"}]},
    {id:"stranger",title:"The Stranger Who Is Not Lost",tags:["person","choice"],body:"Someone sits beside the path polishing a pair of muddy boots. “You look lost,” they say. “I'm not. I'm exactly where I meant to be.”",prompt:"Write 350 words about whether your protagonist asks for help, offers help, or keeps walking.",min:350,success:[{flag:"helpedStranger",label:"Made a connection with the stranger"}]},
    {id:"child",title:"The Child Who Isn't Lost",tags:["person","mystery"],body:"A child stands beside a signpost, calmly eating a pear. They know the names of every path, but insist that none of the paths lead anywhere.",prompt:"Write 350 words about what the child wants and what your protagonist recognizes in them.",min:350,success:[{flag:"metChild",label:"Met the child"}]},
    {id:"double",title:"The Person Who Looks Like You",tags:["person","mystery"],body:"Someone emerges between the trees with your face, your voice, and a small, exhausted smile. “You're taking longer this time,” they say.",prompt:"Write 400 words about what this double knows that your protagonist doesn't—or what they are pretending to know.",min:400,success:[{flag:"metDouble",label:"Met your double"}]},
    {id:"feather",title:"The Blue Feather",tags:["object","choice"],body:"A blue feather rests on a stone. It is warm to the touch, and when you hold it up, the trees lean slightly in your direction.",prompt:"Write 300 words about whether your protagonist keeps the feather, leaves it as a marker, or gives it to someone else.",min:300,success:[{flag:"acceptedFeather",label:"Accepted the blue feather"}]},
    {id:"map",title:"The Map That Updates",tags:["object","discovery"],body:"A folded map lies beneath a root. As you look at it, a tiny ink path slowly draws itself from your position toward a place marked only with a green dot.",prompt:"Write 350 words about where the map leads and what changes on it when your protagonist makes a decision.",min:350,success:[{flag:"foundMap",label:"Found the changing map"}]},
    {id:"second-moon",title:"The Second Moon",tags:["mystery","environment"],body:"Through a gap in the canopy, you see two moons. One hangs in the sky. The other is reflected in a puddle—and moves when you do.",prompt:"Write 350 words about what the second moon reveals when your protagonist looks away from it.",min:350,success:[{flag:"sawSecondMoon",label:"Saw the second moon"}]},
    {id:"voice",title:"The Voice Underground",tags:["mystery","environment"],body:"Something beneath the roots whispers your protagonist's name. Then it whispers a name they have never told anyone.",prompt:"Write 400 words about whether your protagonist answers the voice and what it asks them to remember.",min:400,success:[{flag:"heardVoice",label:"Heard the voice underground"}]},
    {id:"door",title:"The Door Between Trees",tags:["mystery","choice"],requires:["foundKey"],body:"Between two old trees stands a narrow wooden door. There is no wall, no frame, and no visible hinge. The key in your pocket has begun to grow warm.",prompt:"Write 400 words about what lies beyond the door and whether your protagonist chooses to open it.",min:400,success:[{flag:"openedDoor",label:"Opened the door between trees"}]},
    {id:"cupboard",title:"The Locked Cupboard",tags:["object","discovery"],requires:["foundCottage","foundKey"],body:"The iron key turns in the cottage cupboard. Inside is a small glass jar holding a firefly that shines like a star, and a letter addressed to whoever opens the door.",prompt:"Write 350 words about the letter and what your protagonist decides to do with the impossible firefly.",min:350,success:[{flag:"openedCupboard",label:"Opened the locked cupboard"}]},
    {id:"cottage-journal",title:"The Cottage Journal",tags:["place","object"],requires:["foundCottage"],body:"The journal's pages are filled with accounts of people entering the woods. The last entry describes someone who made the exact choice your protagonist just made.",prompt:"Write 400 words about what the journal reveals and whether your protagonist believes its author.",min:400,success:[{flag:"readJournal",label:"Read the cottage journal"}]},
    {id:"fox-gift",title:"A Gift for the Fox",tags:["animal","choice"],requires:["helpedFox"],body:"The fox returns carrying a tiny object in its mouth. It places the object at your feet, then waits for you to understand that this is a gift.",prompt:"Write 300 words about the gift and why the fox believes your protagonist needs it.",min:300,success:[{flag:"foxGift",label:"Received a gift from the fox"}]},
    {id:"watcher",title:"The Watcher at the Tree Line",tags:["mystery","environment"],body:"The forest goes quiet. Between the trunks, something watches you without moving. You cannot tell whether it is keeping you here or keeping something else away.",prompt:"Write 400 words about what your protagonist does when they realize the Watcher has been nearby for a long time.",min:400,success:[{flag:"sawWatcher",label:"Faced the Watcher"}]},
    {id:"clearing",title:"The Old Clearing",tags:["place","discovery"],body:"An enormous tree rises from the middle of a clearing. Its roots curl around a stone marked with a single sentence: YOU HAVE BEEN HERE BEFORE.",prompt:"Write 400 words about the memory the tree gives your protagonist—or the memory it refuses to return.",min:400,success:[{flag:"rememberedForest",label:"Received a memory from the old tree"}]},
    {id:"keeper",title:"The Keeper of Paths",tags:["person","mystery"],body:"A figure in a coat stitched with leaves waits at a crossroads. “The forest has been telling me about you,” they say. “I would like to hear your version.”",prompt:"Write 450 words about what the Keeper has heard and how your protagonist explains their choices.",min:450,success:[{flag:"metForestKeeper",label:"Met the Keeper of Paths"}]},
    {id:"roots",title:"The Thing Beneath the Roots",tags:["mystery","environment"],body:"At the forest's heart, the ground rises and falls as if something beneath it is breathing. A voice asks what your protagonist believes the forest has been protecting.",prompt:"Write 500 words revealing what lies beneath the roots. It can be a creature, a memory, a person, a promise, or something your protagonist cannot name.",min:500,success:[{flag:"answeredForest",label:"Answered the forest's question"}]},
    {id:"shortcut",title:"The Shortcut",tags:["choice","place"],body:"A narrow path slopes sharply downhill. It would save hours, but every footprint on it faces toward you—even the ones you haven't made yet.",prompt:"Write 350 words about whether your protagonist takes the shortcut or chooses the slower, safer-looking path.",min:350,success:[{flag:"tookShortcut",label:"Chose the shortcut"}]},
    {id:"leave-something",title:"Leave Something Behind",tags:["choice","object"],body:"A flat stone sits beside the path. Someone has arranged small objects on it: a button, a ribbon, a coin, and a smooth white pebble. There is room for one more.",prompt:"Write 300 words about what your protagonist leaves behind and why the forest might keep it.",min:300,success:[{flag:"leftOffering",label:"Left an offering"}]}
  ]
};